---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false
configure_dock: true

dotfiles_repo: https://github.com/mattstruble/dotfiles.git
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.dotfiles

dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - "App Store"
  - "System Settings"
  - Finder

homebrew_taps:
  - homebrew/cask-fonts
  - 1password/tap

homebrew_installed_packages:
  - ansible-lint
  - awscli
  - aws-shell
  - bibtex2html
  - bibtexconv
  - biber
  - black
  - checkmake
  - cowsay
  - curl
  - fd
  - fortune
  - gh
  - git
  - gnupg2
  - groovy
  - koekeishiya/formulae/skhd
  - koekeishiya/formulae/yabai
  - lazygit
  - markdown-toc
  - markdownlint-cli
  - npm
  - nvim
  - pinentry-mac
  - prettier
  - pyenv
  - pyenv-virtualenv
  - pyright
  - python3
  - pyyaml
  - reattach-to-user-namespace
  - ripgrep
  - ruff
  - ruff-lsp
  - shellcheck
  - shellharden
  - stow
  - sqlite
  - terraform
  - tmux
  - tree-sitter
  - uncrustify
  - vulture
  - wget
  - write-good
  - yaml-language-server
  - yamllint
  - yarn
  - ykman
  - yubikey-agent
  - yubikey-personalization
  - zsh-history-substring-search
  - zsh-syntax-highlighting
  - zsh-autosuggestions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - docker
  # - firefox
  - font-meslo-lg-nerd-font
  - iterm2
  - sublime-text
  - sublime-merge
  - scroll-reverser
  - obsidian
  - flux
  - godot
  - discord
  - yubico-yubikey-manager
  - vagrant
  - arc 
  - wacom-tablet

configure_sublime: false

mas_email: ""
mas_password: ""
mas_installed_apps:
  - { id: 595191960, name: "CopyClip" }
  - { id: 1452453066, name: "Hidden Bar" }
  - { id: 1472777122, name: "PayPal Honey" }
  - { id: 1611378436, name: "Pure Paste" }
  - { id: 1355679052, name: "Dropover" }
  - { id: 803453959, name: "Slack" }
  - { id: 1607635845, name: "Velja" }
  - { id: 1452453066, name: "Hidden Bar" }

composer_packages: []
gem_packages: []
npm_packages: []

pip_packages:
  - name: pynvim
  - name: neovim
