---
- name: Configure host
  gather_facts: true
  hosts: all

  vars_files:
    - config.yml

  roles:
    # - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    # - role: geerlingguy.dotfiles
    #   when: configure_dotfiles
    #   tags: ["dotfiles"]
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ["mas"]
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]

  tasks:
    # - import_tasks: tasks/osx.yml
    #   when: configure_osx
    #   tags: ["osx"]

    - import_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]

    - import_tasks: tasks/stow.yml
      tags: ["dotfiles"]
