---
name: CI
"on":
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 4

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install linters
        run: pip3 install yamllint ansible ansible-lint

      - name: Lint code
        run: |
          yamllint .
          ansible-lint
          ansible-playbook main.yml --syntax-check

  integration:
    name: Integration
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Remove existing brew
        run: |
          curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
          chmod +x ./uninstall.sh
          sudo ./uninstall.sh --force

          sudo rm -rf /usr/local/Homebrew
          sudo rm -rf /usr/local/Caskroom
          sudo rm -rf /usr/local/bin/brew

      - name: Remove built-in browsers
        run: |
          sudo rm -rf /Applications/Firefox.app
          sudo rm -rf /Applications/Google\ Chrome.app
          sudo rm -rf /usr/local/bin/firefox

      - name: Test playbook
        run: make run
        env:
          ANSIBLE_FORCE_COLOR: "1"

      - name: Test Idempotence
        run: |
          idempotence=$(mktemp)
          make run | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: "1"
